/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) S550_dob_func_expl_vde_adj_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_s3 CASADI_PREFIX(s3)
#define casadi_sq CASADI_PREFIX(sq)
#define casadi_zeros CASADI_PREFIX(zeros)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};
static const casadi_int casadi_s3[20] = 
  {19, 1, 0, 16, 3, 4, 5, 6,
  7, 8, 9, 10, 11, 12, 13, 14,
  15, 16, 17, 18};

static const casadi_real casadi_zeros[13] = 
  {0., 0., 0., 0., 0., 0., 0., 0.,
  0., 0., 0., 0., 0.};

/* S550_dob_func_expl_vde_adj:(i0[13],i1[13],i2[6],i3[3])->(o0[19x1,16nz]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w01=w+17, *w03=w+23, *w04=w+27, *w05=w+30, *w06=w+34, w07, w08, *w09=w+52, *w10=w+56, *w11=w+72, *w12=w+76;
  casadi_real *w13=w+80, w14, w15, w16, w17, w18, w19, w20, w21, w22, w23, w24;
  casadi_real w25, w26, w27, *w28=w+98, *w29=w+107, *w30=w+110, *w31=w+119, *w32=w+122, w33, w34, w35, w36;
  const casadi_real *cs, *ct, *wr00, *wr01, *wr02, *wr03, *wr04;
  /* #0: @0 = input[1][0] */
  wr00 = arg[1] ? arg[1] : casadi_zeros;
  /* #1: {@1, @2, @3, @4} = vertsplit(@0) */
  wr01 = wr00;
  wr02 = wr00+3;
  wr03 = wr00+6;
  wr04 = wr00+10;
  /* #2: output[0][0] = @1 */
  casadi_copy(wr01, 3, res[0]);
  /* #3: @5 = zeros(4x1) */
  casadi_clear(w05, 4);
  /* #4: @6 = zeros(4x4) */
  casadi_clear(w06, 16);
  /* #5: @7 = 0.5 */
  w07 = 5.0000000000000000e-01;
  /* #6: @3 = (@7*@3) */
  for (i=0, rr=w03, cs=wr03; i<4; ++i) (*rr++)  = (w07*(*cs++));
  /* #7: @8 = 0 */
  w08 = 0.;
  /* #8: @1 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w01);
  /* #9: @9 = vertcat(@8, @1) */
  rr=w09;
  *rr++ = w08;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  /* #10: @9 = @9' */
  /* #11: @6 = mac(@3,@9,@6) */
  for (i=0, rr=w06; i<4; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w03+j, ct=w09+i*1; k<1; ++k) *rr += cs[k*4]**ct++;
  /* #12: @10 = @6' */
  for (i=0, rr=w10, cs=w06; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #13: {@9, @11, @12, @13} = horzsplit(@10) */
  casadi_copy(w10, 4, w09);
  casadi_copy(w10+4, 4, w11);
  casadi_copy(w10+8, 4, w12);
  casadi_copy(w10+12, 4, w13);
  /* #14: @13 = @13' */
  /* #15: {@14, @15, @16, @17} = horzsplit(@13) */
  w14 = w13[0];
  w15 = w13[1];
  w16 = w13[2];
  w17 = w13[3];
  /* #16: @12 = @12' */
  /* #17: {@18, @19, @20, @21} = horzsplit(@12) */
  w18 = w12[0];
  w19 = w12[1];
  w20 = w12[2];
  w21 = w12[3];
  /* #18: @14 = (@14+@19) */
  w14 += w19;
  /* #19: @11 = @11' */
  /* #20: {@19, @22, @23, @24} = horzsplit(@11) */
  w19 = w11[0];
  w22 = w11[1];
  w23 = w11[2];
  w24 = w11[3];
  /* #21: @14 = (@14-@23) */
  w14 -= w23;
  /* #22: @9 = @9' */
  /* #23: {@23, @25, @26, @27} = horzsplit(@9) */
  w23 = w09[0];
  w25 = w09[1];
  w26 = w09[2];
  w27 = w09[3];
  /* #24: @14 = (@14-@27) */
  w14 -= w27;
  /* #25: @9 = @5; (@9[3] += @14) */
  casadi_copy(w05, 4, w09);
  for (rr=w09+3, cs=(&w14); rr!=w09+4; rr+=1) *rr += *cs++;
  /* #26: @18 = (@18-@15) */
  w18 -= w15;
  /* #27: @18 = (@18+@24) */
  w18 += w24;
  /* #28: @18 = (@18-@26) */
  w18 -= w26;
  /* #29: (@9[2] += @18) */
  for (rr=w09+2, cs=(&w18); rr!=w09+3; rr+=1) *rr += *cs++;
  /* #30: @16 = (@16-@21) */
  w16 -= w21;
  /* #31: @16 = (@16+@19) */
  w16 += w19;
  /* #32: @16 = (@16-@25) */
  w16 -= w25;
  /* #33: (@9[1] += @16) */
  for (rr=w09+1, cs=(&w16); rr!=w09+2; rr+=1) *rr += *cs++;
  /* #34: @17 = (@17+@20) */
  w17 += w20;
  /* #35: @17 = (@17+@22) */
  w17 += w22;
  /* #36: @17 = (@17+@23) */
  w17 += w23;
  /* #37: (@9[0] += @17) */
  for (rr=w09+0, cs=(&w17); rr!=w09+1; rr+=1) *rr += *cs++;
  /* #38: @11 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w11);
  /* #39: @17 = @11[1] */
  for (rr=(&w17), cs=w11+1; cs!=w11+2; cs+=1) *rr++ = *cs;
  /* #40: @28 = zeros(3x3) */
  casadi_clear(w28, 9);
  /* #41: @23 = input[2][0] */
  w23 = arg[2] ? arg[2][0] : 0;
  /* #42: @22 = input[2][1] */
  w22 = arg[2] ? arg[2][1] : 0;
  /* #43: @23 = (@23+@22) */
  w23 += w22;
  /* #44: @22 = input[2][2] */
  w22 = arg[2] ? arg[2][2] : 0;
  /* #45: @23 = (@23+@22) */
  w23 += w22;
  /* #46: @22 = input[2][3] */
  w22 = arg[2] ? arg[2][3] : 0;
  /* #47: @23 = (@23+@22) */
  w23 += w22;
  /* #48: @22 = input[2][4] */
  w22 = arg[2] ? arg[2][4] : 0;
  /* #49: @23 = (@23+@22) */
  w23 += w22;
  /* #50: @22 = input[2][5] */
  w22 = arg[2] ? arg[2][5] : 0;
  /* #51: @23 = (@23+@22) */
  w23 += w22;
  /* #52: @29 = vertcat(@8, @8, @23) */
  rr=w29;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w23;
  /* #53: @8 = 2.9 */
  w08 = 2.8999999999999999e+00;
  /* #54: @29 = (@29/@8) */
  for (i=0, rr=w29; i<3; ++i) (*rr++) /= w08;
  /* #55: @29 = @29' */
  /* #56: @28 = mac(@2,@29,@28) */
  for (i=0, rr=w28; i<3; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=wr02+j, ct=w29+i*1; k<1; ++k) *rr += cs[k*3]**ct++;
  /* #57: @30 = @28' */
  for (i=0, rr=w30, cs=w28; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #58: {@29, @31, @32} = horzsplit(@30) */
  casadi_copy(w30, 3, w29);
  casadi_copy(w30+3, 3, w31);
  casadi_copy(w30+6, 3, w32);
  /* #59: @32 = @32' */
  /* #60: {@8, @23, @22} = horzsplit(@32) */
  w08 = w32[0];
  w23 = w32[1];
  w22 = w32[2];
  /* #61: @23 = (2.*@23) */
  w23 = (2.* w23 );
  /* #62: @20 = (@17*@23) */
  w20  = (w17*w23);
  /* #63: @16 = @11[2] */
  for (rr=(&w16), cs=w11+2; cs!=w11+3; cs+=1) *rr++ = *cs;
  /* #64: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #65: @25 = (@16*@8) */
  w25  = (w16*w08);
  /* #66: @20 = (@20-@25) */
  w20 -= w25;
  /* #67: @31 = @31' */
  /* #68: {@25, @19, @21} = horzsplit(@31) */
  w25 = w31[0];
  w19 = w31[1];
  w21 = w31[2];
  /* #69: @21 = (2.*@21) */
  w21 = (2.* w21 );
  /* #70: @18 = (@17*@21) */
  w18  = (w17*w21);
  /* #71: @20 = (@20-@18) */
  w20 -= w18;
  /* #72: @18 = @11[3] */
  for (rr=(&w18), cs=w11+3; cs!=w11+4; cs+=1) *rr++ = *cs;
  /* #73: @25 = (2.*@25) */
  w25 = (2.* w25 );
  /* #74: @26 = (@18*@25) */
  w26  = (w18*w25);
  /* #75: @20 = (@20+@26) */
  w20 += w26;
  /* #76: @29 = @29' */
  /* #77: {@26, @24, @15} = horzsplit(@29) */
  w26 = w29[0];
  w24 = w29[1];
  w15 = w29[2];
  /* #78: @15 = (2.*@15) */
  w15 = (2.* w15 );
  /* #79: @14 = (@16*@15) */
  w14  = (w16*w15);
  /* #80: @20 = (@20+@14) */
  w20 += w14;
  /* #81: @24 = (2.*@24) */
  w24 = (2.* w24 );
  /* #82: @14 = (@18*@24) */
  w14  = (w18*w24);
  /* #83: @20 = (@20-@14) */
  w20 -= w14;
  /* #84: (@9[0] += @20) */
  for (rr=w09+0, cs=(&w20); rr!=w09+1; rr+=1) *rr += *cs++;
  /* #85: @20 = (2.*@17) */
  w20 = (2.* w17 );
  /* #86: @22 = (-@22) */
  w22 = (- w22 );
  /* #87: @22 = (2.*@22) */
  w22 = (2.* w22 );
  /* #88: @14 = (@20*@22) */
  w14  = (w20*w22);
  /* #89: @27 = @11[0] */
  for (rr=(&w27), cs=w11+0; cs!=w11+1; cs+=1) *rr++ = *cs;
  /* #90: @33 = (@27*@23) */
  w33  = (w27*w23);
  /* #91: @14 = (@14+@33) */
  w14 += w33;
  /* #92: @33 = (@18*@8) */
  w33  = (w18*w08);
  /* #93: @14 = (@14+@33) */
  w14 += w33;
  /* #94: @33 = (@27*@21) */
  w33  = (w27*w21);
  /* #95: @14 = (@14-@33) */
  w14 -= w33;
  /* #96: @19 = (-@19) */
  w19 = (- w19 );
  /* #97: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #98: @20 = (@20*@19) */
  w20 *= w19;
  /* #99: @14 = (@14+@20) */
  w14 += w20;
  /* #100: @20 = (@16*@25) */
  w20  = (w16*w25);
  /* #101: @14 = (@14+@20) */
  w14 += w20;
  /* #102: @20 = (@18*@15) */
  w20  = (w18*w15);
  /* #103: @14 = (@14+@20) */
  w14 += w20;
  /* #104: @20 = (@16*@24) */
  w20  = (w16*w24);
  /* #105: @14 = (@14+@20) */
  w14 += w20;
  /* #106: (@9[1] += @14) */
  for (rr=w09+1, cs=(&w14); rr!=w09+2; rr+=1) *rr += *cs++;
  /* #107: @14 = (@16*@23) */
  w14  = (w16*w23);
  /* #108: @20 = (@17*@8) */
  w20  = (w17*w08);
  /* #109: @14 = (@14+@20) */
  w14 += w20;
  /* #110: @20 = (@16*@21) */
  w20  = (w16*w21);
  /* #111: @14 = (@14+@20) */
  w14 += w20;
  /* #112: @20 = (2.*@18) */
  w20 = (2.* w18 );
  /* #113: @19 = (@20*@19) */
  w19  = (w20*w19);
  /* #114: @14 = (@14+@19) */
  w14 += w19;
  /* #115: @19 = (@27*@25) */
  w19  = (w27*w25);
  /* #116: @14 = (@14+@19) */
  w14 += w19;
  /* #117: @19 = (@17*@15) */
  w19  = (w17*w15);
  /* #118: @14 = (@14+@19) */
  w14 += w19;
  /* #119: @19 = (@27*@24) */
  w19  = (w27*w24);
  /* #120: @14 = (@14-@19) */
  w14 -= w19;
  /* #121: @26 = (-@26) */
  w26 = (- w26 );
  /* #122: @26 = (2.*@26) */
  w26 = (2.* w26 );
  /* #123: @20 = (@20*@26) */
  w20 *= w26;
  /* #124: @14 = (@14+@20) */
  w14 += w20;
  /* #125: (@9[3] += @14) */
  for (rr=w09+3, cs=(&w14); rr!=w09+4; rr+=1) *rr += *cs++;
  /* #126: @14 = (2.*@16) */
  w14 = (2.* w16 );
  /* #127: @22 = (@14*@22) */
  w22  = (w14*w22);
  /* #128: @23 = (@18*@23) */
  w23  = (w18*w23);
  /* #129: @22 = (@22+@23) */
  w22 += w23;
  /* #130: @8 = (@27*@8) */
  w08  = (w27*w08);
  /* #131: @22 = (@22-@8) */
  w22 -= w08;
  /* #132: @21 = (@18*@21) */
  w21  = (w18*w21);
  /* #133: @22 = (@22+@21) */
  w22 += w21;
  /* #134: @25 = (@17*@25) */
  w25  = (w17*w25);
  /* #135: @22 = (@22+@25) */
  w22 += w25;
  /* #136: @15 = (@27*@15) */
  w15  = (w27*w15);
  /* #137: @22 = (@22+@15) */
  w22 += w15;
  /* #138: @24 = (@17*@24) */
  w24  = (w17*w24);
  /* #139: @22 = (@22+@24) */
  w22 += w24;
  /* #140: @14 = (@14*@26) */
  w14 *= w26;
  /* #141: @22 = (@22+@14) */
  w22 += w14;
  /* #142: (@9[2] += @22) */
  for (rr=w09+2, cs=(&w22); rr!=w09+3; rr+=1) *rr += *cs++;
  /* #143: output[0][1] = @9 */
  if (res[0]) casadi_copy(w09, 4, res[0]+3);
  /* #144: @29 = zeros(3x1) */
  casadi_clear(w29, 3);
  /* #145: @22 = -0.5 */
  w22 = -5.0000000000000000e-01;
  /* #146: @14 = @1[2] */
  for (rr=(&w14), cs=w01+2; cs!=w01+3; cs+=1) *rr++ = *cs;
  /* #147: @31 = (-@4) */
  for (i=0, rr=w31, cs=wr04; i<3; ++i) *rr++ = (- *cs++ );
  /* #148: {@26, @24, NULL} = vertsplit(@31) */
  w26 = w31[0];
  w24 = w31[1];
  /* #149: @15 = (@14*@24) */
  w15  = (w14*w24);
  /* #150: @15 = (@22*@15) */
  w15  = (w22*w15);
  /* #151: @31 = @29; (@31[0] += @15) */
  casadi_copy(w29, 3, w31);
  for (rr=w31+0, cs=(&w15); rr!=w31+1; rr+=1) *rr += *cs++;
  /* #152: @15 = @1[0] */
  for (rr=(&w15), cs=w01+0; cs!=w01+1; cs+=1) *rr++ = *cs;
  /* #153: @22 = (@22*@15) */
  w22 *= w15;
  /* #154: @22 = (@22*@24) */
  w22 *= w24;
  /* #155: @24 = @1[1] */
  for (rr=(&w24), cs=w01+1; cs!=w01+2; cs+=1) *rr++ = *cs;
  /* #156: @24 = (@7*@24) */
  w24  = (w07*w24);
  /* #157: @24 = (@24*@26) */
  w24 *= w26;
  /* #158: @22 = (@22+@24) */
  w22 += w24;
  /* #159: (@31[2] += @22) */
  for (rr=w31+2, cs=(&w22); rr!=w31+3; rr+=1) *rr += *cs++;
  /* #160: @14 = (@14*@26) */
  w14 *= w26;
  /* #161: @7 = (@7*@14) */
  w07 *= w14;
  /* #162: (@31[1] += @7) */
  for (rr=w31+1, cs=(&w07); rr!=w31+2; rr+=1) *rr += *cs++;
  /* #163: @7 = (-@17) */
  w07 = (- w17 );
  /* #164: @14 = (-@16) */
  w14 = (- w16 );
  /* #165: @26 = (-@18) */
  w26 = (- w18 );
  /* #166: @9 = horzcat(@27, @7, @14, @26) */
  rr=w09;
  *rr++ = w27;
  *rr++ = w07;
  *rr++ = w14;
  *rr++ = w26;
  /* #167: @9 = @9' */
  /* #168: @11 = horzcat(@17, @27, @26, @16) */
  rr=w11;
  *rr++ = w17;
  *rr++ = w27;
  *rr++ = w26;
  *rr++ = w16;
  /* #169: @11 = @11' */
  /* #170: @12 = horzcat(@16, @18, @27, @7) */
  rr=w12;
  *rr++ = w16;
  *rr++ = w18;
  *rr++ = w27;
  *rr++ = w07;
  /* #171: @12 = @12' */
  /* #172: @13 = horzcat(@18, @14, @17, @27) */
  rr=w13;
  *rr++ = w18;
  *rr++ = w14;
  *rr++ = w17;
  *rr++ = w27;
  /* #173: @13 = @13' */
  /* #174: @10 = horzcat(@9, @11, @12, @13) */
  rr=w10;
  for (i=0, cs=w09; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w11; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w12; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w13; i<4; ++i) *rr++ = *cs++;
  /* #175: @5 = mac(@10,@3,@5) */
  for (i=0, rr=w05; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w10+j, ct=w03+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #176: {NULL, @1} = vertsplit(@5) */
  casadi_copy(w05+1, 3, w01);
  /* #177: @31 = (@31+@1) */
  for (i=0, rr=w31, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #178: output[0][2] = @31 */
  if (res[0]) casadi_copy(w31, 3, res[0]+7);
  /* #179: @31 = input[3][0] */
  casadi_copy(arg[3], 3, w31);
  /* #180: @14 = @31[1] */
  for (rr=(&w14), cs=w31+1; cs!=w31+2; cs+=1) *rr++ = *cs;
  /* #181: @7 = 16.6667 */
  w07 = 1.6666666666666668e+01;
  /* #182: {@26, @22, @24} = vertsplit(@4) */
  w26 = wr04[0];
  w22 = wr04[1];
  w24 = wr04[2];
  /* #183: @22 = (@7*@22) */
  w22  = (w07*w22);
  /* #184: @14 = (@14*@22) */
  w14 *= w22;
  /* #185: @15 = @31[2] */
  for (rr=(&w15), cs=w31+2; cs!=w31+3; cs+=1) *rr++ = *cs;
  /* #186: @7 = (@7*@26) */
  w07 *= w26;
  /* #187: @15 = (@15*@7) */
  w15 *= w07;
  /* #188: @14 = (@14-@15) */
  w14 -= w15;
  /* #189: @15 = 0.01569 */
  w15 = 1.5689999999999999e-02;
  /* #190: @26 = 11.1111 */
  w26 = 1.1111111111111111e+01;
  /* #191: @26 = (@26*@24) */
  w26 *= w24;
  /* #192: @15 = (@15*@26) */
  w15 *= w26;
  /* #193: @26 = (@14-@15) */
  w26  = (w14-w15);
  /* #194: @24 = 0.866025 */
  w24 = 8.6602540378443860e-01;
  /* #195: @25 = 0.265 */
  w25 = 2.6500000000000001e-01;
  /* #196: @22 = (@25*@22) */
  w22  = (w25*w22);
  /* #197: @24 = (@24*@22) */
  w24 *= w22;
  /* #198: @22 = (@26-@24) */
  w22  = (w26-w24);
  /* #199: @21 = 0.5 */
  w21 = 5.0000000000000011e-01;
  /* #200: @25 = (@25*@7) */
  w25 *= w07;
  /* #201: @21 = (@21*@25) */
  w21 *= w25;
  /* #202: @22 = (@22+@21) */
  w22 += w21;
  /* #203: @7 = 0.344828 */
  w07 = 3.4482758620689657e-01;
  /* #204: @8 = 1 */
  w08 = 1.;
  /* #205: @23 = sq(@16) */
  w23 = casadi_sq( w16 );
  /* #206: @20 = sq(@18) */
  w20 = casadi_sq( w18 );
  /* #207: @19 = (@23+@20) */
  w19  = (w23+w20);
  /* #208: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #209: @19 = (@8-@19) */
  w19  = (w08-w19);
  /* #210: @33 = (@17*@16) */
  w33  = (w17*w16);
  /* #211: @34 = (@27*@18) */
  w34  = (w27*w18);
  /* #212: @33 = (@33-@34) */
  w33 -= w34;
  /* #213: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #214: @35 = (@17*@18) */
  w35  = (w17*w18);
  /* #215: @36 = (@27*@16) */
  w36  = (w27*w16);
  /* #216: @35 = (@35+@36) */
  w35 += w36;
  /* #217: @35 = (2.*@35) */
  w35 = (2.* w35 );
  /* #218: @31 = horzcat(@19, @33, @35) */
  rr=w31;
  *rr++ = w19;
  *rr++ = w33;
  *rr++ = w35;
  /* #219: @31 = @31' */
  /* #220: @19 = (@16*@17) */
  w19  = (w16*w17);
  /* #221: @19 = (@19+@34) */
  w19 += w34;
  /* #222: @19 = (2.*@19) */
  w19 = (2.* w19 );
  /* #223: @34 = sq(@17) */
  w34 = casadi_sq( w17 );
  /* #224: @20 = (@34+@20) */
  w20  = (w34+w20);
  /* #225: @20 = (2.*@20) */
  w20 = (2.* w20 );
  /* #226: @20 = (@8-@20) */
  w20  = (w08-w20);
  /* #227: @33 = (@16*@18) */
  w33  = (w16*w18);
  /* #228: @27 = (@27*@17) */
  w27 *= w17;
  /* #229: @33 = (@33-@27) */
  w33 -= w27;
  /* #230: @33 = (2.*@33) */
  w33 = (2.* w33 );
  /* #231: @4 = horzcat(@19, @20, @33) */
  rr=w04;
  *rr++ = w19;
  *rr++ = w20;
  *rr++ = w33;
  /* #232: @4 = @4' */
  /* #233: @17 = (@18*@17) */
  w17  = (w18*w17);
  /* #234: @17 = (@17-@36) */
  w17 -= w36;
  /* #235: @17 = (2.*@17) */
  w17 = (2.* w17 );
  /* #236: @18 = (@18*@16) */
  w18 *= w16;
  /* #237: @18 = (@18+@27) */
  w18 += w27;
  /* #238: @18 = (2.*@18) */
  w18 = (2.* w18 );
  /* #239: @34 = (@34+@23) */
  w34 += w23;
  /* #240: @34 = (2.*@34) */
  w34 = (2.* w34 );
  /* #241: @8 = (@8-@34) */
  w08 -= w34;
  /* #242: @1 = horzcat(@17, @18, @8) */
  rr=w01;
  *rr++ = w17;
  *rr++ = w18;
  *rr++ = w08;
  /* #243: @1 = @1' */
  /* #244: @30 = horzcat(@31, @4, @1) */
  rr=w30;
  for (i=0, cs=w31; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w04; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w01; i<3; ++i) *rr++ = *cs++;
  /* #245: @29 = mac(@30,@2,@29) */
  for (i=0, rr=w29; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w30+j, ct=wr02+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #246: @29 = (@7*@29) */
  for (i=0, rr=w29, cs=w29; i<3; ++i) (*rr++)  = (w07*(*cs++));
  /* #247: {NULL, NULL, @7} = vertsplit(@29) */
  w07 = w29[2];
  /* #248: @22 = (@22+@7) */
  w22 += w07;
  /* #249: output[0][3] = @22 */
  if (res[0]) res[0][10] = w22;
  /* #250: @14 = (@14+@15) */
  w14 += w15;
  /* #251: @15 = (@14+@25) */
  w15  = (w14+w25);
  /* #252: @15 = (@15+@7) */
  w15 += w07;
  /* #253: output[0][4] = @15 */
  if (res[0]) res[0][11] = w15;
  /* #254: @15 = (@26+@24) */
  w15  = (w26+w24);
  /* #255: @15 = (@15+@21) */
  w15 += w21;
  /* #256: @15 = (@15+@7) */
  w15 += w07;
  /* #257: output[0][5] = @15 */
  if (res[0]) res[0][12] = w15;
  /* #258: @15 = (@14+@24) */
  w15  = (w14+w24);
  /* #259: @15 = (@15-@21) */
  w15 -= w21;
  /* #260: @15 = (@15+@7) */
  w15 += w07;
  /* #261: output[0][6] = @15 */
  if (res[0]) res[0][13] = w15;
  /* #262: @26 = (@26-@25) */
  w26 -= w25;
  /* #263: @26 = (@26+@7) */
  w26 += w07;
  /* #264: output[0][7] = @26 */
  if (res[0]) res[0][14] = w26;
  /* #265: @14 = (@14-@24) */
  w14 -= w24;
  /* #266: @14 = (@14-@21) */
  w14 -= w21;
  /* #267: @14 = (@14+@7) */
  w14 += w07;
  /* #268: output[0][8] = @14 */
  if (res[0]) res[0][15] = w14;
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_vde_adj_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_vde_adj_release(int mem) {
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_vde_adj_incref(void) {
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_vde_adj_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int S550_dob_func_expl_vde_adj_n_in(void) { return 4;}

CASADI_SYMBOL_EXPORT casadi_int S550_dob_func_expl_vde_adj_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real S550_dob_func_expl_vde_adj_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* S550_dob_func_expl_vde_adj_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    case 3: return "i3";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* S550_dob_func_expl_vde_adj_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* S550_dob_func_expl_vde_adj_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s0;
    case 2: return casadi_s1;
    case 3: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* S550_dob_func_expl_vde_adj_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s3;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8;
  if (sz_res) *sz_res = 5;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 129;
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_vde_adj_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 8*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 5*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 129*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
