/* This file was automatically generated by CasADi 3.7.2.
 *  It consists of: 
 *   1) content generated by CasADi runtime: not copyrighted
 *   2) template code copied from CasADi source: permissively licensed (MIT-0)
 *   3) user code: owned by the user
 *
 */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) S550_dob_func_expl_ode_fun_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int int
#endif

/* Add prefix to internal symbols */
#define casadi_c0 CASADI_PREFIX(c0)
#define casadi_clear CASADI_PREFIX(clear)
#define casadi_copy CASADI_PREFIX(copy)
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

void casadi_copy(const casadi_real* x, casadi_int n, casadi_real* y) {
  casadi_int i;
  if (y) {
    if (x) {
      for (i=0; i<n; ++i) *y++ = *x++;
    } else {
      for (i=0; i<n; ++i) *y++ = 0.;
    }
  }
}

void casadi_clear(casadi_real* x, casadi_int n) {
  casadi_int i;
  if (x) {
    for (i=0; i<n; ++i) *x++ = 0;
  }
}

casadi_real casadi_sq(casadi_real x) { return x*x;}

static const casadi_int casadi_s0[3] = {13, 1, 1};
static const casadi_int casadi_s1[3] = {6, 1, 1};
static const casadi_int casadi_s2[3] = {3, 1, 1};

static const casadi_real casadi_c0[3] = {0., 0., -9.8100000000000005e+00};

/* S550_dob_func_expl_ode_fun:(i0[13],i1[6],i2[3])->(o0[13]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_int i, j, k;
  casadi_real *rr, *w00=w+4, *w01=w+7, w02, *w03=w+11, w04, w05, w06, w07, w08, w09, w10;
  casadi_real w11, w12, w13, w14, *w15=w+26, *w16=w+29, *w17=w+32, *w18=w+35, *w19=w+44, w20, w21, w22;
  casadi_real w23, *w24=w+57, *w25=w+61, *w26=w+65, *w27=w+69, *w28=w+73, *w29=w+89;
  const casadi_real *cs, *ct;
  /* #0: @0 = input[0][1] */
  casadi_copy(arg[0] ? arg[0]+3 : 0, 3, w00);
  /* #1: output[0][0] = @0 */
  casadi_copy(w00, 3, res[0]);
  /* #2: @0 = [0, 0, -9.81] */
  casadi_copy(casadi_c0, 3, w00);
  /* #3: @1 = zeros(3x1) */
  casadi_clear(w01, 3);
  /* #4: @2 = 1 */
  w02 = 1.;
  /* #5: @3 = input[0][2] */
  casadi_copy(arg[0] ? arg[0]+6 : 0, 4, w03);
  /* #6: @4 = @3[2] */
  for (rr=(&w04), cs=w03+2; cs!=w03+3; cs+=1) *rr++ = *cs;
  /* #7: @5 = sq(@4) */
  w05 = casadi_sq( w04 );
  /* #8: @6 = @3[3] */
  for (rr=(&w06), cs=w03+3; cs!=w03+4; cs+=1) *rr++ = *cs;
  /* #9: @7 = sq(@6) */
  w07 = casadi_sq( w06 );
  /* #10: @8 = (@5+@7) */
  w08  = (w05+w07);
  /* #11: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #12: @8 = (@2-@8) */
  w08  = (w02-w08);
  /* #13: @9 = @3[1] */
  for (rr=(&w09), cs=w03+1; cs!=w03+2; cs+=1) *rr++ = *cs;
  /* #14: @10 = (@9*@4) */
  w10  = (w09*w04);
  /* #15: @11 = @3[0] */
  for (rr=(&w11), cs=w03+0; cs!=w03+1; cs+=1) *rr++ = *cs;
  /* #16: @12 = (@11*@6) */
  w12  = (w11*w06);
  /* #17: @10 = (@10-@12) */
  w10 -= w12;
  /* #18: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #19: @13 = (@9*@6) */
  w13  = (w09*w06);
  /* #20: @14 = (@11*@4) */
  w14  = (w11*w04);
  /* #21: @13 = (@13+@14) */
  w13 += w14;
  /* #22: @13 = (2.*@13) */
  w13 = (2.* w13 );
  /* #23: @15 = horzcat(@8, @10, @13) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w10;
  *rr++ = w13;
  /* #24: @15 = @15' */
  /* #25: @8 = (@4*@9) */
  w08  = (w04*w09);
  /* #26: @8 = (@8+@12) */
  w08 += w12;
  /* #27: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #28: @12 = sq(@9) */
  w12 = casadi_sq( w09 );
  /* #29: @7 = (@12+@7) */
  w07  = (w12+w07);
  /* #30: @7 = (2.*@7) */
  w07 = (2.* w07 );
  /* #31: @7 = (@2-@7) */
  w07  = (w02-w07);
  /* #32: @10 = (@4*@6) */
  w10  = (w04*w06);
  /* #33: @13 = (@11*@9) */
  w13  = (w11*w09);
  /* #34: @10 = (@10-@13) */
  w10 -= w13;
  /* #35: @10 = (2.*@10) */
  w10 = (2.* w10 );
  /* #36: @16 = horzcat(@8, @7, @10) */
  rr=w16;
  *rr++ = w08;
  *rr++ = w07;
  *rr++ = w10;
  /* #37: @16 = @16' */
  /* #38: @8 = (@6*@9) */
  w08  = (w06*w09);
  /* #39: @8 = (@8-@14) */
  w08 -= w14;
  /* #40: @8 = (2.*@8) */
  w08 = (2.* w08 );
  /* #41: @14 = (@6*@4) */
  w14  = (w06*w04);
  /* #42: @14 = (@14+@13) */
  w14 += w13;
  /* #43: @14 = (2.*@14) */
  w14 = (2.* w14 );
  /* #44: @12 = (@12+@5) */
  w12 += w05;
  /* #45: @12 = (2.*@12) */
  w12 = (2.* w12 );
  /* #46: @2 = (@2-@12) */
  w02 -= w12;
  /* #47: @17 = horzcat(@8, @14, @2) */
  rr=w17;
  *rr++ = w08;
  *rr++ = w14;
  *rr++ = w02;
  /* #48: @17 = @17' */
  /* #49: @18 = horzcat(@15, @16, @17) */
  rr=w18;
  for (i=0, cs=w15; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w16; i<3; ++i) *rr++ = *cs++;
  for (i=0, cs=w17; i<3; ++i) *rr++ = *cs++;
  /* #50: @19 = @18' */
  for (i=0, rr=w19, cs=w18; i<3; ++i) for (j=0; j<3; ++j) rr[i+j*3] = *cs++;
  /* #51: @8 = 0 */
  w08 = 0.;
  /* #52: @14 = input[1][0] */
  w14 = arg[1] ? arg[1][0] : 0;
  /* #53: @2 = input[1][1] */
  w02 = arg[1] ? arg[1][1] : 0;
  /* #54: @12 = (@14+@2) */
  w12  = (w14+w02);
  /* #55: @5 = input[1][2] */
  w05 = arg[1] ? arg[1][2] : 0;
  /* #56: @12 = (@12+@5) */
  w12 += w05;
  /* #57: @13 = input[1][3] */
  w13 = arg[1] ? arg[1][3] : 0;
  /* #58: @12 = (@12+@13) */
  w12 += w13;
  /* #59: @7 = input[1][4] */
  w07 = arg[1] ? arg[1][4] : 0;
  /* #60: @12 = (@12+@7) */
  w12 += w07;
  /* #61: @10 = input[1][5] */
  w10 = arg[1] ? arg[1][5] : 0;
  /* #62: @12 = (@12+@10) */
  w12 += w10;
  /* #63: @15 = vertcat(@8, @8, @12) */
  rr=w15;
  *rr++ = w08;
  *rr++ = w08;
  *rr++ = w12;
  /* #64: @20 = 2.9 */
  w20 = 2.8999999999999999e+00;
  /* #65: @15 = (@15/@20) */
  for (i=0, rr=w15; i<3; ++i) (*rr++) /= w20;
  /* #66: @1 = mac(@19,@15,@1) */
  for (i=0, rr=w01; i<1; ++i) for (j=0; j<3; ++j, ++rr) for (k=0, cs=w19+j, ct=w15+i*3; k<3; ++k) *rr += cs[k*3]**ct++;
  /* #67: @0 = (@0+@1) */
  for (i=0, rr=w00, cs=w01; i<3; ++i) (*rr++) += (*cs++);
  /* #68: output[0][1] = @0 */
  if (res[0]) casadi_copy(w00, 3, res[0]+3);
  /* #69: @20 = 0.5 */
  w20 = 5.0000000000000000e-01;
  /* #70: @3 = zeros(4x1) */
  casadi_clear(w03, 4);
  /* #71: @21 = (-@9) */
  w21 = (- w09 );
  /* #72: @22 = (-@4) */
  w22 = (- w04 );
  /* #73: @23 = (-@6) */
  w23 = (- w06 );
  /* #74: @24 = horzcat(@11, @21, @22, @23) */
  rr=w24;
  *rr++ = w11;
  *rr++ = w21;
  *rr++ = w22;
  *rr++ = w23;
  /* #75: @24 = @24' */
  /* #76: @25 = horzcat(@9, @11, @23, @4) */
  rr=w25;
  *rr++ = w09;
  *rr++ = w11;
  *rr++ = w23;
  *rr++ = w04;
  /* #77: @25 = @25' */
  /* #78: @26 = horzcat(@4, @6, @11, @21) */
  rr=w26;
  *rr++ = w04;
  *rr++ = w06;
  *rr++ = w11;
  *rr++ = w21;
  /* #79: @26 = @26' */
  /* #80: @27 = horzcat(@6, @22, @9, @11) */
  rr=w27;
  *rr++ = w06;
  *rr++ = w22;
  *rr++ = w09;
  *rr++ = w11;
  /* #81: @27 = @27' */
  /* #82: @28 = horzcat(@24, @25, @26, @27) */
  rr=w28;
  for (i=0, cs=w24; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w25; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w26; i<4; ++i) *rr++ = *cs++;
  for (i=0, cs=w27; i<4; ++i) *rr++ = *cs++;
  /* #83: @29 = @28' */
  for (i=0, rr=w29, cs=w28; i<4; ++i) for (j=0; j<4; ++j) rr[i+j*4] = *cs++;
  /* #84: @0 = input[0][3] */
  casadi_copy(arg[0] ? arg[0]+10 : 0, 3, w00);
  /* #85: @24 = vertcat(@8, @0) */
  rr=w24;
  *rr++ = w08;
  for (i=0, cs=w00; i<3; ++i) *rr++ = *cs++;
  /* #86: @3 = mac(@29,@24,@3) */
  for (i=0, rr=w03; i<1; ++i) for (j=0; j<4; ++j, ++rr) for (k=0, cs=w29+j, ct=w24+i*4; k<4; ++k) *rr += cs[k*4]**ct++;
  /* #87: @3 = (@20*@3) */
  for (i=0, rr=w03, cs=w03; i<4; ++i) (*rr++)  = (w20*(*cs++));
  /* #88: output[0][2] = @3 */
  if (res[0]) casadi_copy(w03, 4, res[0]+6);
  /* #89: @6 = 0.265 */
  w06 = 2.6500000000000001e-01;
  /* #90: @22 = 0.5 */
  w22 = 5.0000000000000011e-01;
  /* #91: @9 = (@14+@5) */
  w09  = (w14+w05);
  /* #92: @9 = (@22*@9) */
  w09  = (w22*w09);
  /* #93: @9 = (@9+@2) */
  w09 += w02;
  /* #94: @11 = (@13+@10) */
  w11  = (w13+w10);
  /* #95: @22 = (@22*@11) */
  w22 *= w11;
  /* #96: @9 = (@9-@22) */
  w09 -= w22;
  /* #97: @9 = (@9-@7) */
  w09 -= w07;
  /* #98: @9 = (@6*@9) */
  w09  = (w06*w09);
  /* #99: @22 = 0.06 */
  w22 = 5.9999999999999998e-02;
  /* #100: @9 = (@9/@22) */
  w09 /= w22;
  /* #101: @11 = 0.866025 */
  w11 = 8.6602540378443860e-01;
  /* #102: @4 = (@5+@13) */
  w04  = (w05+w13);
  /* #103: @4 = (@11*@4) */
  w04  = (w11*w04);
  /* #104: @21 = (@14+@10) */
  w21  = (w14+w10);
  /* #105: @11 = (@11*@21) */
  w11 *= w21;
  /* #106: @4 = (@4-@11) */
  w04 -= w11;
  /* #107: @6 = (@6*@4) */
  w06 *= w04;
  /* #108: @6 = (@6/@22) */
  w06 /= w22;
  /* #109: @4 = 0.01569 */
  w04 = 1.5689999999999999e-02;
  /* #110: @2 = (@2-@14) */
  w02 -= w14;
  /* #111: @2 = (@2-@5) */
  w02 -= w05;
  /* #112: @2 = (@2+@13) */
  w02 += w13;
  /* #113: @2 = (@2-@7) */
  w02 -= w07;
  /* #114: @2 = (@2+@10) */
  w02 += w10;
  /* #115: @4 = (@4*@2) */
  w04 *= w02;
  /* #116: @2 = 0.09 */
  w02 = 8.9999999999999997e-02;
  /* #117: @4 = (@4/@2) */
  w04 /= w02;
  /* #118: @1 = vertcat(@9, @6, @4) */
  rr=w01;
  *rr++ = w09;
  *rr++ = w06;
  *rr++ = w04;
  /* #119: @9 = @0[1] */
  for (rr=(&w09), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #120: @20 = (@20*@9) */
  w20 *= w09;
  /* #121: @9 = @0[2] */
  for (rr=(&w09), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #122: @20 = (@20*@9) */
  w20 *= w09;
  /* #123: @6 = -0.5 */
  w06 = -5.0000000000000000e-01;
  /* #124: @4 = @0[0] */
  for (rr=(&w04), cs=w00+0; cs!=w00+1; cs+=1) *rr++ = *cs;
  /* #125: @6 = (@6*@4) */
  w06 *= w04;
  /* #126: @6 = (@6*@9) */
  w06 *= w09;
  /* #127: @0 = vertcat(@20, @6, @8) */
  rr=w00;
  *rr++ = w20;
  *rr++ = w06;
  *rr++ = w08;
  /* #128: @1 = (@1-@0) */
  for (i=0, rr=w01, cs=w00; i<3; ++i) (*rr++) -= (*cs++);
  /* #129: @0 = input[2][0] */
  casadi_copy(arg[2], 3, w00);
  /* #130: @20 = @0[2] */
  for (rr=(&w20), cs=w00+2; cs!=w00+3; cs+=1) *rr++ = *cs;
  /* #131: @20 = (@20*@12) */
  w20 *= w12;
  /* #132: @20 = (@20/@22) */
  w20 /= w22;
  /* #133: @20 = (-@20) */
  w20 = (- w20 );
  /* #134: @6 = @0[1] */
  for (rr=(&w06), cs=w00+1; cs!=w00+2; cs+=1) *rr++ = *cs;
  /* #135: @6 = (@6*@12) */
  w06 *= w12;
  /* #136: @6 = (@6/@22) */
  w06 /= w22;
  /* #137: @0 = vertcat(@20, @6, @8) */
  rr=w00;
  *rr++ = w20;
  *rr++ = w06;
  *rr++ = w08;
  /* #138: @1 = (@1+@0) */
  for (i=0, rr=w01, cs=w00; i<3; ++i) (*rr++) += (*cs++);
  /* #139: output[0][3] = @1 */
  if (res[0]) casadi_copy(w01, 3, res[0]+10);
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_ode_fun_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_ode_fun_release(int mem) {
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_ode_fun_incref(void) {
}

CASADI_SYMBOL_EXPORT void S550_dob_func_expl_ode_fun_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int S550_dob_func_expl_ode_fun_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int S550_dob_func_expl_ode_fun_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real S550_dob_func_expl_ode_fun_default_in(casadi_int i) {
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* S550_dob_func_expl_ode_fun_name_in(casadi_int i) {
  switch (i) {
    case 0: return "i0";
    case 1: return "i1";
    case 2: return "i2";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* S550_dob_func_expl_ode_fun_name_out(casadi_int i) {
  switch (i) {
    case 0: return "o0";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* S550_dob_func_expl_ode_fun_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* S550_dob_func_expl_ode_fun_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7;
  if (sz_res) *sz_res = 2;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 105;
  return 0;
}

CASADI_SYMBOL_EXPORT int S550_dob_func_expl_ode_fun_work_bytes(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 7*sizeof(const casadi_real*);
  if (sz_res) *sz_res = 2*sizeof(casadi_real*);
  if (sz_iw) *sz_iw = 0*sizeof(casadi_int);
  if (sz_w) *sz_w = 105*sizeof(casadi_real);
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
