l1_adaptive:
  dob_looptime: 0.010
  As_array: [-0.1, -0.1, -0.1,    # vx, vy, vz (Body frame)
             -0.1, -0.1, -0.1]    # wx, wy ,wz (Body frame)
  freq_cutoff_trans: 60.0
  freq_cutoff_rot: 60.0

lpf:
  lin_vel_cutoff: 20.0
  ang_vel_cutoff: 60.0